import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Roboto_Flex as Roboto, Montserrat, Poppins } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/Header'
import { ReduxProvider } from '@/redux/provider'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  variable: '--font-roboto',
})

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--font-montserrat',
})

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: 'Tripeverywhere',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${montserrat.variable} ${poppins.variable} bg-background font-sans`}
      >
        <ReduxProvider>
          <Header />
          {children}
        </ReduxProvider>
      </body>
    </html>
  )
}
